import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";

import localFont from "next/font/local";
import Footer from "@/app/components/footer";

// Font files can be colocated inside of `pages`
//const myFont = localFont({ src: "./GeneralSans-Regular.woff2" });

const myFont = localFont({
  src: "./GeneralSans-Regular.woff2",
  variable: "--font-myFont",
});

/**
 * Loads a local font file named "neueregular.ttf" and assigns it to the CSS variable "--font-neueRegular".
 * This font can then be used throughout the application by referencing the CSS variable.
 */
const neueRegular = localFont({
  src: "./neueregular.ttf",
  variable: "--font-neueRegular",
});

export const metadata: Metadata = {
  title: "Cowork",
  description: "Generated by create next app",
};

// Font files can be colocated inside of `app`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${myFont.variable} ${neueRegular.variable} font-myFont`}
    >
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
